mybatis:
  mapper-locations: classpath:mapper/*.xml

# oracle 配置
db:
  driver: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@docker:1521:XE
  username: AfterSales
  password: oracle_pwd

spring:
  profiles:
    active: oracle
  datasource:
    driver-class-name: ${db.driver}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
