multi:
  datasource:
    druid:
      # 是否使用druid 连接池来创建数据源
      enabled: false

multi4601:
  datasource:
    druid:
      # druid 连接池配置
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://docker:3306/multi_datasource_master?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
        username: root
        password: root
        initial-size: 10
        max-active: 30
        min-idle: 10
        max-wait: 2000
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://docker:3306/multi_datasource_slave?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
        username: root
        password: root
        initial-size: 10
        max-active: 30
        min-idle: 10
        max-wait: 2000
    # 普通连接配置
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://docker:3306/multi_datasource_master?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
      username: root
      password: root
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://docker:3306/multi_datasource_slave?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
      username: root
      password: root

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.suyh4601.mapper.master.MasterTestUserMapper: debug
    com.suyh4601.mapper.slave.SlaveTestUserMapper: debug

# 参考博客：https://www.cnblogs.com/itfeng813/p/14657415.html
# 若同一个项目中有多个数据源需要进行版本管理，则需要放弃application.properties中的配置，
# 并且配置flyway.enabled=false,禁止springboot自动的调用flyway.migrate()方法。然后增加配置类，手动调用migrate()方法即可。
spring:
  flyway:
    enabled: false
