spring:
  autoconfigure:
    # 默认它会去创建RedisProperties 这个bean 对象，会跟我自定义的冲突。
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisReactiveAutoConfiguration
  data:
    redis:
      repositories:
        # 需要禁用
        enabled: false

suyh:
  redis:
    other:
      client-type: lettuce
      database: 2
      host: 43.139.78.193
      port: 6789
      password: Hq5nq95BMFzGncxP
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 500
          min-idle: 0
      lettuce:
        shutdown-timeout: 0
        pool:
          enabled: true
    business:
      client-type: lettuce
      database: 3
      host: 43.139.78.193
      port: 6789
      password: Hq5nq95BMFzGncxP
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 500
          min-idle: 0
      lettuce:
        shutdown-timeout: 0
        pool:
          enabled: true



