spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.34:3306/flink-cds-suyh?useSSL=false&characterEncoding=UTF-8
    username: flink-cds-suyh
    password: flink-cds-suyh



