server:
  port: 13202

# The transport client support is deprecated. Use other supported clients instead.
# spring.data.elasticsearch.repositories.enabled
spring:
  autoconfigure:
    exclude:
      # 看源代码这个应该是过期了
      # 它依赖 ElasticsearchProperties 这个配置属性，而这个配置属性已经过期了
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchAutoConfiguration
      # Reactive 这个是响应链式编程，我们这里应该是没用到，所以直接排除掉即可
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveRestClientAutoConfiguration
      # 它是直接被标记为过期的了，直接排除
      - org.springframework.boot.autoconfigure.elasticsearch.jest.JestAutoConfiguration
  profiles:
    include:
#      - disable-es
      - enable-es


# 下面演示禁用所有指标，
#  仅启用db指标：
management:
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    # org.springframework.boot spring-boot-actuator-autoconfigure 项目中自动装配了如下三个健康检查
    #  org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticSearchClientHealthContributorAutoConfiguration
    #  org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticSearchJestHealthContributorAutoConfiguration
    #  org.springframework.boot.actuate.autoconfigure.elasticsearch.ElasticSearchRestHealthContributorAutoConfiguration
    elasticsearch:
      enabled: false
    redis:
      enabled: false
    mongo:
      enabled: false
    solr:
      enabled: false


