# 禁用ES 的配置文件

# The transport client support is deprecated. Use other supported clients instead.
# spring.data.elasticsearch.repositories.enabled
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
      - org.springframework.boot.autoconfigure.elasticsearch.rest.RestClientAutoConfiguration

com:
  suyh:
    es:
      enable: false





