server:
  port: 13202


# The transport client support is deprecated. Use other supported clients instead.
# spring.data.elasticsearch.repositories.enabled
spring:
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200
      connection-timeout: 1s
      read-timeout: 30s
  autoconfigure:
    exclude:
      # 看源代码这个应该是过期了
      # 它依赖 ElasticsearchProperties 这个配置属性，而这个配置属性已经过期了
      - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchAutoConfiguration
      # 这个我倒是没太清楚，只是排除掉了似乎功能并没有受到影响，先保留着，不排除吧。
      # - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchRepositoriesAutoConfiguration
      # Reactive 这个是响应链式编程，我们这里应该是没用到，所以直接排除掉即可
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveElasticsearchRepositoriesAutoConfiguration
      - org.springframework.boot.autoconfigure.data.elasticsearch.ReactiveRestClientAutoConfiguration
      # 它是直接被标记为过期的了，直接排除
      - org.springframework.boot.autoconfigure.elasticsearch.jest.JestAutoConfiguration
      # 下面两个是需要的不能被排除掉，我们现在使用的就是它们两自动配置的bean 功能
      # - org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration
      # - org.springframework.boot.autoconfigure.elasticsearch.rest.RestClientAutoConfiguration



