
# 日志文件配置，应用配置文件中的配置比，日志配置文件中的配置优先级更高。
logging:
  file:
    name: /mastermile/logs/mastermile-admin.log # 日志文件名，全路径
  logback:
    rollingpolicy:
      clean-history-on-start: true
      file-name-pattern: /mastermile/logs/%d{yyyy-MM-dd}/mastermile-admin.%03i.log
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 0B


---
spring:
  config:
    activate:
      on-profile: local

# 日志文件配置
logging:
  level:
    root: debug
  file:
    # 本地日志直接在项目的目录下面存放就好了。
    name: logs/mastermile-admin.log # 日志文件名，全路径
  logback:
    rollingpolicy:
      clean-history-on-start: true
      # 本地日志直接在项目的目录下面存放就好了。
      file-name-pattern: logs/%d{yyyy-MM-dd}/mastermile-admin.%03i.log




