spring:
  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  redis:
    host: www.suyh.com.cn
    port: 6379 # 端口
    password: 123456
    database: 0 # 数据库索引
    lettuce:
      pool:
        # lettuce 的连接池，需要额外引入commons-pool2 组件
        enabled: true


  cache:
    type: redis
    # CacheManager 中如果配置了时间，则优先级会比这里高。
    redis:
      # 参数的类型是 Duration, 参考：Duration.parse(...)
      time-to-live: PT60S
      cache-null-values: false
      # 注意CacheManager 的优先级
      key-prefix: 'suyh-prefix:'


---
#########################################################################################
# local 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: local

---
#########################################################################################
# dev 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: dev

---
#########################################################################################
# sit 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: sit

---
#########################################################################################
# perf 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: perf

---
#########################################################################################
# uat 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: uat


---
#########################################################################################
# pro 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: pro


