spring:
  flyway:
    # 是否开户flywaydb, 默认值：true
    enabled: true
    # 配置SQL指定脚本位置
    locations: classpath:db/migrate/single
    # 当需要低版本的脚本时，需要置成true，否则只能执行高版本的脚本, 默认为: false
    outOfOrder: true
    # 有数据的数据库请保留此值为true，禁用clean命令，执行clean命令会清空数据库
    cleanDisabled: true
    # 记录migrate历史记录的表名，默认为 flyway_schema_history
    table: schema_version_history
    # TODO: 下面的这些配置没有找到，不知道为什么没有。是有其他配置代替了吗？
    # migrate前后需要做某些操作时可使用此配置项，值为类名(带包路径)，多个类名之间使用逗号分隔
    # 每个类需要实现org.flywaydb.core.api.callback.Callback接口
    # flyway.callbacks=com.everhomes.dbmigrate.core.MigrateCallBack
    #
    #
    # 配置数据库连接，注意在url中不要配置用户名和密码
    #    url: jdbc:mysql://192.168.127.143:3306/suyh_db?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    #    user: root
    #    password: root
    # 当数据库不是空数据库时，需要配置为true，空数据库则可以不配置。默认值：false
    baselineOnMigrate: false
    # 配置了该版本后，migrate会从比该版本大的版本进行migrate，不配置时默认值为1
    baselineVersion: 1
    # 迁移时是否校验，默认值：true
    validateOnMigrate: true
  datasource:
    url: jdbc:mysql://docker:3306/suyh_single_datasource_hikari_cp?characterEncoding=utf-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    # 参考博客：https://blog.csdn.net/zl1zl2zl3/article/details/105633844
    # HikariCP 自定义配置&#xff0c;对应 HikariConfig 配置属性类
    hikari:
      minimum-idle: 1 # 池中维护的最小空闲连接数&#xff0c;默认为 10 个。
      maximum-pool-size: 13 # 池中最大连接数&#xff0c;包括闲置和使用中的连接&#xff0c;默认为 10 个。
      idle-timeout: 10000
      max-lifetime: 30000
  profiles:
    active: HikariCP

server:
  port: 14602
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.suyh4601.mapper.master.MasterTestUserMapper: debug
    com.suyh4601.mapper.slave.SlaveTestUserMapper: debug



