server:
  port: 8080
  servlet:
    context-path: /suyh
spring:
  profiles:
    active: dev
# common 组件的logback-spring.xml 中定义的变量，这里填充变量值
logback:
  file:
    dir: @project.basedir@/logs
    prefix: filter-interceptor