
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.127.143:3306/suyh_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nullCatalogMeansCurrent=true
    password: root
    username: root
  flyway:
    # 是否开户flywaydb, 默认值：true
    enabled: true
    # 配置SQL指定脚本位置
    locations: classpath:db/migration/mysql
    # 当需要低版本的脚本时，需要置成true，否则只能执行高版本的脚本, 默认为: false
    outOfOrder: true
    # 有数据的数据库请保留此值为true，禁用clean命令，执行clean命令会清空数据库
    cleanDisabled: true
    # 记录migrate历史记录的表名，默认为 flyway_schema_history
    table: schema_version_history
    # 当数据库不是空数据库时，需要配置为true，空数据库则可以不配置。默认值：false
    baselineOnMigrate: false
    # 配置了该版本后，migrate会从比该版本大的版本进行migrate，不配置时默认值为1
    baselineVersion: 1
    # 迁移时是否校验，默认值：true
    validateOnMigrate: true
  jpa:
    # 操作数据库时显示sql语句，默认值: false
    show-sql: true
    # 在程序启动时自动创建相关的表, 默认值: false
    generate-ddl: false
    hibernate:
      # 程序启用时，对表的操作。none 不要做任何操作。即保留之前操作的数据库表中的数据
      ddl-auto: none
logging:
  pattern:
    console: level-%level %msg%n
  # 有个问题，下面的这些日志等级是console 的呢，还是说console 与logfile都一样的？
  level:
    root: info
    org.hiibernate: info
    # 在show-sql为true时，显示SQL 中的动态参数值
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 在show-sql为true时，显示查询结果
    org.hibernate.hql.internal.ast.exec.BasicExecutor: trace
    com.suyh2901: debug

# 这个工程不需要创建web 应用，这里的测试都是通过TEST 进行单元测试的
#server:
#  port: 12901