spring:
  redis:
    host: 192.168.127.136
    port: 7002
    # 数据库连接超时时间，2.0 中该参数的类型为Duration,这里在配置的时候需要指明单位
    timeout: 10000
    # 如果需要密码，则可以使用配置来指定
    # spring.redis.password=
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

