server:
  port: 8080
spring:
  profiles:
#    active: ${spring_profiles_active}
    active: dev

application:
  groupId: "@project.groupId@"
  artifactId: "@project.artifactId@"
logging:
  # common组件中添加的日志配置文件
  config: classpath:logback-spring.xml
# common 组件的logback-spring.xml 中定义的变量，这里填充变量值
logback:
  file:
    dir: @project.basedir@/logs
    prefix: profile

