spring:
  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  redis:
    host: suyh-localhost.e3.luyouxia.net
    port: 11477 # 端口
    database: 0 # 数据库索引


#    client-type: lettuce
#    cluster:
#      nodes:
#        - 192.168.1.1:6379
#        - 192.168.1.2:6379
#        - 192.168.1.3:6379
#        - 192.168.1.4:6379
#        - 192.168.1.5:6379
#        - 192.168.1.6:6379
#    password: ${j2c.redis.password:app!12345678}

---
#########################################################################################
# local 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: local

---
#########################################################################################
# dev 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: dev

---
#########################################################################################
# sit 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: sit

---
#########################################################################################
# perf 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: perf

---
#########################################################################################
# uat 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: uat


---
#########################################################################################
# pro 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: pro


