spring:
  datasource:
    read:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://docker:3306/suyh_db?characterEncoding=utf-8&useSSL=false
      username: root
      password: root
    write:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://docker:3306/suyh_db?characterEncoding=utf-8&useSSL=false
      username: root
      password: root


