



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://isuyh.com:3306/suyh-conditionalOnMapper?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: suyh-conditionalOnMapper
    password: suyh-conditionalOnMapper

