
logging:
  level:
    root: info
  file:
    name: /app/logs/overseas-proxy/overseas-proxy.log # 日志文件名，全路径
  logback:
    rollingpolicy:
      clean-history-on-start: true
      file-name-pattern: /app/logs/overseas-proxy/%d{yyyy-MM-dd}/overseas-proxy.%03i.log
      max-file-size: 20MB



---
spring:
  config:
    activate:
      on-profile: suyh


logging:
  level:
    root: debug
  file:
    name: /Users/suyunhong/suyh-develop/logs/overseas-proxy/overseas-proxy.log # 日志文件名，全路径
  logback:
    rollingpolicy:
      clean-history-on-start: true
      file-name-pattern: /Users/suyunhong/suyh-develop/logs/overseas-proxy/%d{yyyy-MM-dd}/overseas-proxy.%03i.log
      max-file-size: 20MB



