spring:
  config:
    import:
      - application-jackson.yaml
      - application-log.yaml
      - application-messageSource.yaml
      - application-swagger.yaml
      - application-web.yaml
  profiles:
    active: suyh





