
logging:
  level:
    root: info
  file:
    name: /app/logs/common-web/common-web.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      file-name-pattern: /app/logs/common-web/%d{yyyy-MM-dd}/common-web.%02i.log
      max-file-size: 20MB



---
spring:
  config:
    activate:
      on-profile: suyh


logging:
  level:
    root: debug
  file:
    name: /Users/suyunhong/suyh-develop/logs/common-web/common-web.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      file-name-pattern: /Users/suyunhong/suyh-develop/logs/common-web/%d{yyyy-MM-dd}/common-web.%02i.log
      max-file-size: 20MB



