# 这里也是统一的配置，对spring web 的@RequestBody与@ResponseBody 这些进行json的序列化与反序列化的一些问题
spring:
  jackson:
    # 配置对默认的@RequestBody和@ResponseBody的json配置
    # 这样我们就不需要在每一个日期上面添加@format 注解就可以将其按下面的配置进行格式化
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: Asia/Shanghai
    defaultPropertyInclusion: always   #非空属性才序列化
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false # 未定义的key不序列化
    serialization:
      # 格式化输出
      indent_output: true
      # 忽略无法转换的对象
      fail_on_empty_beans: false
      # 序列化时，使用时间戳的格式 进行序列化，而不是字符串。
      # write-dates-as-timestamps: true
    parser:
      # 允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      # 允许出现单引号
      allow_single_quotes: true