spring:
  main:
    # 对于有些时候我们不想启用web 服务，而只想使用spring-boot 时，可以禁用web 功能。
    web-application-type: servlet

server:
  servlet:
    context-path: /base/web
  port: 8806

  error:
    # spring mvc 的默认异常处理，可以添加或者禁用一些返回值属性。
    include-binding-errors: always
    include-exception: true
    # message 取的是异常里面的描述字符串
    include-message: always
    include-stacktrace: on_param
#  tomcat:
##    basedir: /suyh/tomcat
#    # tomcat 的访问日志记录
#    # 参考博客：https://blog.csdn.net/wudiyong22/article/details/103849359
#    accesslog:
#      enabled: true
#      directory: accesslog
#      # 用于确定是否将缓冲日志记录的标志。如果为false，则将在每个请求之后写入访问日志。默认值；true
#      buffered: true
#      # 日志格式
##      pattern: %{Host}i begin=%{begin}t end=%{end}t end=%{msec}t "%U" thread=%I

#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ANT_PATH_MATCHER # 解决 SpringFox 与 SpringBoot 2.6.x 不兼容的问题，参见 SpringFoxHandlerProviderBeanPostProcessor 类

