spring:
  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  redis:
    host: 43.136.74.205
    port: 6789 # 端口
    password: lXwynsTx84e62k6K
    database: 13 # 数据库索引
    lettuce:
      pool:
        # lettuce 的连接池，需要额外引入commons-pool2 组件
        enabled: true

---
#########################################################################################
# local 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: local

---
#########################################################################################
# dev 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: dev

---
#########################################################################################
# sit 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: sit

---
#########################################################################################
# perf 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: perf

---
#########################################################################################
# uat 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: uat


---
#########################################################################################
# pro 环境配置
#########################################################################################
spring:
  config:
    activate:
      on-profile: pro


