server:
  port: 13401
  servlet:
    # 访问上下文
    context-path: /xxx

# 设置info 信息
# 默认访问路径为: http://<host>:${server.port}/[${server.servlet.context-path}]/actuator/info
# 可以修改访问路径为: http://<host>:${management.server.port}/${management.server.servlet.context-path}/${management.endpoints.web.base-path}/info
info:
  # 下面的所有设置都是以key-value 格式配置，且自由配置
  company:
    name: abc
    url: http://www.baidu.com
    address: Beijin China
  author:
    name: 张三
    depart: 研发部
  project:
    group-id: @project.groupId@
    artifact-id: @project.artifactId@
    version: @project.version@

# 修改actuator监控器相关配置
management:
  server:
    port: 13499              # 指定actuator监听的端口号，一般使用默认值: ${server.port}
    servlet:
      context-path: /ooo    # 指定actuator监控器的上下文路径，一般使用默认值: ${server.servlet.context-path}
  endpoints:
    web:
      # http://localhost:13499/ooo/base/info
      # http://localhost:13499/ooo/base/suyh-custom/name/suyh
      base-path: /base      # 指定actuator监控终端的基本路径，一般使用默认值: "actuator"
      exposure:
        # 默认情况只开启两个[health,info]，具体的可以参考开课吧课件中的文档
        include: "*"          # 开启所有监控终端，默认只开启两个基础的监控
        exclude: ["env", "health"]   # 指定要关闭的监控终端
        # exclude:
        # - env
        # - info